const recipes = {
    '😊💧': '😢',  // happy + water = crying
    '😊🌟': '🤩',  // happy + star = star-struck
    '😊🌍': '🌎',  // happy + earth = earth americas
    '🌟💧': '✨',  // star + water = sparkles
    '🌟🌍': '🌠',  // star + earth = shooting star
    '💧🌍': '🌊',  // water + earth = wave
    '😢🌟': '🌈',  // crying + star = rainbow
    '😢💧': '🌧️',  // crying + water = rain cloud
    '🤩✨': '🎆',  // star-struck + sparkles = fireworks
    '🌊🌍': '🏖️',  // wave + earth = beach
    '🌈💧': '🌺',  // rainbow + water = flower
    '🌠🌍': '🎡',  // shooting star + earth = ferris wheel
    '🎆✨': '🎉',  // fireworks + sparkles = party popper
    '🏖️🌺': '🌴',  // beach + flower = palm tree
    '🎡🌟': '🎪',  // ferris wheel + star = circus tent
    '🌍🔥': '🌋',  // earth + fire = volcano
    '💧🔥': '🌫️',  // water + fire = fog
    '🌫️🌟': '💫',  // fog + star = dizzy stars
    '🌫️🌍': '⛅',  // fog + earth = partly cloudy
    '🌧️🌟': '⚡',  // rain cloud + star = lightning
    '🌧️🌈': '🌦️',  // rain + rainbow = sun behind rain cloud
    '🌦️🌊': '🏄',  // rain + wave = surfer
    '🏄🌞': '🌞',  // surfer + sun = sun emoji
    '🌞🌊': '🐚',  // sun + wave = shell
    '🐚🌺': '🐌',  // shell + flower = snail
    '🐌🌟': '✨',  // snail + star = sparkle trail
    '🐌🍂': '🐞',  // snail + leaf = ladybug
    '🐞🍃': '🦋',  // ladybug + leaf = butterfly
    '🌸🍃': '🐝',  // flower + leaf = bee
    '🌞🌸': '🌻',  // sun + flower = sunflower
    '🌻🌊': '🐠',  // sunflower + wave = fish
    '🐠🐚': '🐟',  // fish + shell = tropical fish
    '🌺🌊': '🐳',  // flower + wave = whale
    '🌸🐝': '🍯',  // flower + bee = honey pot
    '🌻🐝': '🧡',  // sunflower + bee = orange heart
    '🌴🐬': '🏝️',  // palm tree + dolphin = island
    '🏝️🌋': '🗾',  // island + volcano = map of japan
    '🏖️⛱️': '🏜️',  // beach + umbrella = desert island
    '⛱️☀️': '🏕️',  // umbrella + sun = campsite
    '🏕️🌌': '🛌',  // campsite + milky way = person in bed
    '⛅🌌': '🌙',  // partly cloudy + milky way = crescent moon
    '☀️🌌': '🌞',  // sun + milky way = bright sun
    '🌙🌌': '🌑',  // moon + milky way = new moon
    '🌑🌟': '🌕',  // new moon + star = full moon
    '🌕🌍': '🌏',  // full moon + earth = earth asia
    '🌏🔥': '🔥',  // earth asia + fire = fire emoji
    '🔥🎆': '🎇',  // fire + fireworks = sparkler
    '🔥🍂': '🔥',  // fire + leaf = burning leaf
    '🍂🌧️': '🍄',  // leaf + rain cloud = mushroom
    '🍄💧': '🍃',  // mushroom + water = green leaf
    '🍃✨': '🌱',  // green leaf + sparkles = seedling
    '🌱🌧️': '🌳',  // seedling + rain = tree
    '🌳🍃': '🍏',  // tree + green leaf = green apple
    '🌳🍂': '🍎',  // tree + orange leaf = red apple
    '🍏🐝': '🍋',  // green apple + bee = lemon
    '🍎🐝': '🍒',  // red apple + bee = cherries
    '🍋🍃': '🍐',  // lemon + leaf = pear
    '🍒✨': '🍇',  // cherries + sparkles = grapes
    '🍇💧': '🍉',  // grapes + water = watermelon
    '🍉🍃': '🥥',  // watermelon + leaf = coconut
    '🥥🌴': '🥥',  // coconut + palm tree = coconut emoji
    '🥥🔥': '🥭',  // coconut + fire = mango
    '🥭🍂': '🍑',  // mango + leaf = peach
    '🍑🍃': '🥭',  // peach + green leaf = mango again (cycle)
    '😊🔥': '🥵',  // happy + fire = hot face
    '😊🍃': '🌿',  // happy + leaf = herb
    '😢🔥': '🥺',  // crying + fire = pleading face
    '🤩🌌': '🌠',  // star-struck + milky way = shooting star
    '😢🌌': '😭',  // crying + milky way = sobbing
    '🤩🌍': '🌍',  // star-struck + earth = earth emoji
};

const startingEmojis = ['😊', '🌟', '🌍', '💧', '🔥', '🍃', '🍂', '🍄', '🌳', '🐝'];
